# Generated by Django 5.2.4 on 2025-07-23 17:58

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='expires_at',
            field=models.DateTimeField(default=files.models.default_expiry),
        ),
    ]
